[package]
name = "rust-js-plugin"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
log = "0.4.27"
oxc_resolver = "11.7.1"
relative-path = "2.0.1"
rquickjs = { version = "0.9.0", features = ["loader"] }
rquickjs-extra = { version = "0.1.1", features = ["console"] }
simple_logger = "5.0.0"
